---
deployment:
  tasks:
    - export DEPLOYPATH=/home/proteccion/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp .nojekyll $DEPLOYPATH
