// Shared bilingual content for the PCC Integrity site
window.PCC_CONTENT = {
  es: {
    nav: {
      home: 'Inicio',
      about: 'Nosotros',
      services: 'Servicios por industria',
      supply: 'Suministro Técnico',
      experience: 'Experiencia',
      esg: 'ESG',
      contact: 'Contacto',
      cta: 'Cotizar un proyecto',
    },
    home: {
      eyebrow: 'DESDE 1978 · COLOMBIA · PERÚ · USA',
      hTitleA: 'Protegemos la infraestructura que',
      hTitleB: 'mueve a Latinoamérica',
      hTitleC: 'contra la corrosión.',
      hSub: 'Ingeniería, suministro, instalación e inspección de sistemas de protección catódica para oleoductos, puertos, plantas industriales y redes eléctricas. Más de 550 proyectos entregados bajo estándares NACE e ISO.',
      ctaPrimary: 'Solicitar cotización',
      ctaSecondary: 'Conocer servicios',
      heroCaption: 'Refinería Cartagena — Colombia',
      sectorEyebrow: 'SERVICIOS POR INDUSTRIA',
      sectorTitle: 'Soluciones integrales para cada entorno operativo.',
      sectorSub: 'Diseño de sistemas a la medida de cada sector, con más de cuatro décadas de experiencia en ambientes críticos.',
      lineEyebrow: 'LÍNEAS DE SERVICIO',
      lineTitle: 'Un equipo. Un contrato. Todo el ciclo de vida del activo.',
      lineSub: 'Desde la ingeniería conceptual hasta el mantenimiento correctivo — sin subcontratar la experiencia técnica.',
      proofEyebrow: 'CONFIANZA',
      proofTitle: 'Operadores de infraestructura crítica en Latinoamérica y EE. UU. confían en PCC.',
      projEyebrow: 'EXPERIENCIA',
      projTitle: 'Proyectos y publicaciones recientes.',
      projAll: 'Ver todos los proyectos',
      ctaBig: '¿Tiene un activo que necesita durar otros 40 años?',
      ctaBigSub: 'Envíenos los planos, coordenadas o el alcance del proyecto. Un ingeniero senior responderá en 48 horas hábiles con una propuesta técnica preliminar.',
    },
    about: {
      eyebrow: 'NOSOTROS',
      title: 'Desde 1978, el estándar en ingeniería de corrosión en Latinoamérica.',
      sub: 'Protección Catódica de Colombia S.A.S. (PCC Integrity) es una firma de ingeniería colombiana especializada en el control de corrosión de infraestructura enterrada, sumergida y marina. Operamos desde Bogotá, Katy (TX) y Lima, con más de 550 proyectos entregados para las industrias de petróleo, gas, energía eléctrica y puertos.',
      mission: 'Misión',
      missionBody: 'Brindar soluciones en ingeniería de corrosión garantizando la satisfacción de las necesidades y requerimientos de los clientes; comercializando y/o desarrollando productos y servicios de excelente calidad en el sector de Oil & Gas, Infraestructura y Marítimo.',
      vision: 'Visión',
      visionBody: 'En los próximos cinco años, la compañía se proyecta como líder del sector en Colombia, con una propuesta de valor basada en la implementación de nuevas tecnologías, apalancada en el conocimiento y la reputación adquiridos. Adicionalmente se consolidará la posición internacional de la compañía en Sudamérica.',
      lemaTitle: 'Nuestro Lema',
      lemaTag: 'fits you',
      lemaBody: 'En Protección Catódica de Colombia hemos fortalecido a lo largo de más de 40 años nuestro capital intelectual y material, para ponerlo al servicio de las necesidades de nuestros clientes. Nuestra promesa es brindar un servicio, producto y asesoría justo a la medida del cliente, apalancados en nuestra amplia experiencia.',
      valuesEyebrow: 'VALORES',
      valuesTitle: 'Lo que define cómo trabajamos.',
    },
    services: {
      eyebrow: 'SERVICIOS POR INDUSTRIA',
      title: 'Cada sector tiene su propio lenguaje de corrosión.',
      sub: 'Ingeniería especializada para los cuatro sectores que conocemos desde dentro. Haga clic en cada industria para ver el alcance técnico detallado.',
    },
    supply: {
      eyebrow: 'SUMINISTRO TÉCNICO',
      title: 'Materiales y equipos críticos para protección catódica.',
      sub: 'En PCC Integrity ofrecemos un servicio integral de suministro de materiales y equipos críticos para protección catódica. Tanto si requiere componentes únicos como un paquete completo de materiales, trabajamos con fabricantes certificados y socios internacionales. Garantizamos calidad total, cumplimiento de estándares NACE e ISO, y durabilidad bajo condiciones marinas, terrestres e industriales exigentes.',
      categoriesTitle: 'Categorías',
      rectifiersTitle: 'PCC Rectifiers',
      rectifiersSub: 'Cinco configuraciones diseñadas para cada entorno operativo.',
    },
    experience: {
      eyebrow: 'EXPERIENCIA',
      title: '+550 proyectos entregados en tres países.',
      sub: 'Portafolio seleccionado de proyectos ejecutados para operadores de infraestructura crítica en Colombia, Perú y Estados Unidos.',
      certTitle: 'Certificaciones',
      certSub: 'Sistemas de gestión certificados bajo los estándares internacionales que exige la industria.',
    },
    esg: {
      eyebrow: 'ESG',
      title: 'Ingeniería responsable, de principio a fin.',
      sub: 'Nuestro compromiso con el medio ambiente, las comunidades donde operamos y la gobernanza corporativa no es un anexo — es parte del servicio que entregamos.',
    },
    contact: {
      eyebrow: 'CONTACTO',
      title: 'Hablemos de su proyecto.',
      sub: 'Solicitudes, cotizaciones técnicas, peticiones o reclamos. Respondemos en menos de 48 horas hábiles.',
      form: {
        first: 'Nombre',
        last: 'Apellido',
        email: 'Correo electrónico',
        company: 'Empresa',
        subject: 'Asunto',
        message: 'Mensaje',
        send: 'Enviar mensaje',
        sent: 'Gracias. Un ingeniero senior le responderá pronto.',
      },
      officesTitle: 'Oficinas principales',
      careersTitle: 'Trabaja con nosotros',
      careersBody: 'Sé parte de nuestro equipo y ayúdanos a seguir innovando en la industria de integridad y control de corrosión. Envía tu hoja de vida a:',
    },
    footer: {
      tagline: 'Expertos en ingeniería de control de corrosión.',
      services: 'Servicios',
      products: 'Productos',
      company: 'Empresa',
      legal: 'Legal',
      rights: 'Todos los derechos reservados.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services by industry',
      supply: 'Technical supply',
      experience: 'Experience',
      esg: 'ESG',
      contact: 'Contact',
      cta: 'Start a project',
    },
    home: {
      eyebrow: 'SINCE 1978 · COLOMBIA · PERU · USA',
      hTitleA: 'We protect the infrastructure that',
      hTitleB: 'keeps Latin America moving',
      hTitleC: 'against corrosion.',
      hSub: 'Engineering, supply, installation and inspection of cathodic protection systems for pipelines, ports, industrial plants and power grids. Over 550 projects delivered under NACE and ISO standards.',
      ctaPrimary: 'Request a quote',
      ctaSecondary: 'Explore services',
      heroCaption: 'Cartagena Refinery — Colombia',
      sectorEyebrow: 'SERVICES BY INDUSTRY',
      sectorTitle: 'Integrated solutions for every operating environment.',
      sectorSub: 'Tailored system design for each sector, backed by four decades of experience in critical environments.',
      lineEyebrow: 'SERVICE LINES',
      lineTitle: 'One team. One contract. The full asset lifecycle.',
      lineSub: 'From conceptual engineering to corrective maintenance — without subcontracting technical expertise.',
      proofEyebrow: 'TRUSTED BY',
      proofTitle: 'Critical infrastructure operators across Latin America and the US rely on PCC.',
      projEyebrow: 'EXPERIENCE',
      projTitle: 'Recent projects and publications.',
      projAll: 'See all projects',
      ctaBig: 'Do you own an asset that needs to last another 40 years?',
      ctaBigSub: 'Send us the drawings, coordinates or scope. A senior engineer will reply within 48 business hours with a preliminary technical proposal.',
    },
    about: {
      eyebrow: 'ABOUT',
      title: 'Since 1978, the standard in corrosion engineering in Latin America.',
      sub: 'Protección Catódica de Colombia S.A.S. (PCC Integrity) is a Colombian engineering firm specialized in corrosion control for buried, submerged and marine infrastructure. We operate from Bogotá, Katy (TX) and Lima, with more than 550 projects delivered for the oil & gas, power, and marine industries.',
      mission: 'Mission',
      missionBody: 'To provide corrosion engineering solutions guaranteeing client satisfaction; commercializing and developing excellent-quality products and services for the Oil & Gas, Infrastructure and Maritime sectors.',
      vision: 'Vision',
      visionBody: 'In the next five years, the company will position itself as a leader of the sector in Colombia, with a value proposition based on the implementation of new technologies, leveraging the knowledge and reputation acquired. Additionally, it will consolidate its international position in South America.',
      lemaTitle: 'Our Motto',
      lemaTag: 'fits you',
      lemaBody: 'At Protección Catódica de Colombia we have strengthened our intellectual and material capital over more than 40 years, placing it at the service of our clients. Our promise is to deliver a service, product and advisory tailored to each client, leveraging our broad field experience.',
      valuesEyebrow: 'VALUES',
      valuesTitle: 'What defines how we work.',
    },
    services: {
      eyebrow: 'SERVICES BY INDUSTRY',
      title: 'Every sector has its own language of corrosion.',
      sub: 'Specialized engineering for the four sectors we know from the inside. Click on each industry for the detailed technical scope.',
    },
    supply: {
      eyebrow: 'TECHNICAL SUPPLY',
      title: 'Critical materials and equipment for cathodic protection.',
      sub: 'PCC Integrity offers an integrated supply service for critical CP materials and equipment. Whether you need single components or a complete materials package, we work with certified manufacturers and international partners. We guarantee full quality, compliance with NACE and ISO standards, and durability under demanding marine, onshore and industrial conditions.',
      categoriesTitle: 'Categories',
      rectifiersTitle: 'PCC Rectifiers',
      rectifiersSub: 'Five configurations designed for every operating environment.',
    },
    experience: {
      eyebrow: 'EXPERIENCE',
      title: '+550 projects delivered across three countries.',
      sub: 'Selected portfolio of projects executed for critical infrastructure operators in Colombia, Peru and the United States.',
      certTitle: 'Certifications',
      certSub: 'Management systems certified under the international standards our industry demands.',
    },
    esg: {
      eyebrow: 'ESG',
      title: 'Responsible engineering, from start to finish.',
      sub: 'Our commitment to the environment, the communities where we operate, and corporate governance is not an annex — it is part of the service we deliver.',
    },
    contact: {
      eyebrow: 'CONTACT',
      title: 'Let\u2019s talk about your project.',
      sub: 'Requests, technical quotes, inquiries or claims. We reply within 48 business hours.',
      form: {
        first: 'First name',
        last: 'Last name',
        email: 'Email',
        company: 'Company',
        subject: 'Subject',
        message: 'Message',
        send: 'Send message',
        sent: 'Thank you. A senior engineer will be in touch shortly.',
      },
      officesTitle: 'Main offices',
      careersTitle: 'Work with us',
      careersBody: 'Join our team and help us keep innovating in the integrity and corrosion control industry. Send your resume to:',
    },
    footer: {
      tagline: 'Experts in corrosion control engineering.',
      services: 'Services',
      products: 'Products',
      company: 'Company',
      legal: 'Legal',
      rights: 'All rights reserved.',
    },
  },
};

window.PCC_DATA = {
  industries: [
    {
      id: 'oil',
      esName: 'Oil & Gas',
      enName: 'Oil & Gas',
      icon: 'fuel',
      photo: 'assets/marine-pcc.jpg',
      esSub: 'Ductos, refinerías y tanques de almacenamiento.',
      enSub: 'Pipelines, refineries and storage tanks.',
      esItems: [
        'CP para ductos de transporte',
        'Sistemas ICCP para tanques de almacenamiento',
        'Evaluación de interferencias eléctricas',
        'Monitoreo remoto y telemetría',
        'Inspecciones de recubrimientos y CP',
        'Obras civiles asociadas a infraestructura de Oil & Gas',
        'Inspecciones de integridad y control de corrosión',
      ],
      enItems: [
        'CP for transport pipelines',
        'ICCP systems for storage tanks',
        'Electrical interference assessment',
        'Remote monitoring and telemetry',
        'Coating and CP inspections',
        'Civil works for Oil & Gas infrastructure',
        'Integrity and corrosion control inspections',
      ],
      image: 'pipeline',
    },
    {
      id: 'power',
      esName: 'Energía eléctrica',
      enName: 'Electric Power',
      icon: 'zap',
      photo: 'assets/power-plant-pcc.png',
      esSub: 'Subestaciones, torres de transmisión y parques fotovoltaicos.',
      enSub: 'Substations, transmission towers and solar farms.',
      esItems: [
        'Estudios y obras de sistemas de puesta a tierra y apantallamiento',
        'Estudios, suministros y construcción de mitigaciones para interferencias AC',
        'Modelación de inducciones para líneas de transmisión',
        'Proyectos de interferencias eléctricas en parques fotovoltaicos',
        'Evaluación de corrosión en estructuras metálicas',
      ],
      enItems: [
        'Grounding and shielding system studies and construction',
        'AC interference mitigation — studies, supply and construction',
        'Induction modeling for transmission lines',
        'Electrical interference projects for solar farms',
        'Corrosion assessment in metallic structures',
      ],
      image: 'power',
    },
    {
      id: 'marine',
      esName: 'Infraestructura marítima',
      enName: 'Marine infrastructure',
      icon: 'anchor',
      photo: 'assets/marine-jetty-pcc.jpg',
      esSub: 'Muelles, pilotes, tablestacados y embarcaciones.',
      enSub: 'Piers, piles, sheet piling and vessels.',
      esItems: [
        'CP para muelles y estructuras portuarias',
        'ICCP y ánodos de sacrificio en embarcaciones',
        'Monitoreo de corrosión marina',
        'Protección de pilotes y tablestacados',
        'Inspecciones submarinas con tecnología especializada',
      ],
      enItems: [
        'CP for piers and port structures',
        'ICCP and sacrificial anodes on vessels',
        'Marine corrosion monitoring',
        'Pile and sheet pile protection',
        'Underwater inspections with specialized technology',
      ],
      image: 'marine',
    },
    {
      id: 'industrial',
      esName: 'Industrial',
      enName: 'Industrial',
      icon: 'factory',
      photo: 'assets/industrial-pcc.png',
      esSub: 'Plantas de proceso, acueductos y concreto armado.',
      enSub: 'Process plants, water networks and reinforced concrete.',
      esItems: [
        'CP en tanques de proceso y almacenamiento',
        'Protección en estructuras de concreto armado',
        'Sistemas en acueductos de tuberías metálicas o concreto pretensado',
        'Plantas de tratamiento de agua',
        'Inspecciones avanzadas y monitoreo',
      ],
      enItems: [
        'CP for process and storage tanks',
        'Protection of reinforced concrete structures',
        'Water networks in metallic or prestressed concrete pipelines',
        'Water treatment plants',
        'Advanced inspections and monitoring',
      ],
      image: 'industrial',
    },
  ],
  serviceLines: [
    { id: 'eng',  icon: 'pencil-ruler',  esName: 'Ingeniería y consultoría', enName: 'Engineering & consulting', esDesc: 'Ingeniería conceptual, básica y de detalle. Estudios de suelo, ensayos de demanda de corriente, planos y memorias.', enDesc: 'Conceptual, basic and detail engineering. Soil studies, current demand testing, drawings and technical reports.' },
    { id: 'sup',  icon: 'package',        esName: 'Suministro de materiales', enName: 'Materials & equipment supply', esDesc: 'Rectificadores, ánodos, recubrimientos, resinas epóxicas, cintas y unidades de monitoreo remoto.', enDesc: 'Rectifiers, anodes, coatings, epoxy resins, tapes and remote monitoring units.' },
    { id: 'ins',  icon: 'hard-hat',       esName: 'Instalación y mantenimiento', enName: 'Installation & maintenance', esDesc: 'Instalación onshore y offshore; mantenimiento preventivo y correctivo; ensayos On/Off; reparación de rectificadores.', enDesc: 'Onshore and offshore installation; preventive and corrective maintenance; On/Off testing; rectifier repair.' },
    { id: 'cip',  icon: 'search-check',   esName: 'Inspección especializada', enName: 'Specialized inspection', esDesc: 'CIPS (Close Interval Potential Survey), DCVG (Direct Current Voltage Gradient), PCM (Pipeline Current Mapper).', enDesc: 'CIPS (Close Interval Potential Survey), DCVG (Direct Current Voltage Gradient), PCM (Pipeline Current Mapper).' },
  ],
  products: [
    { sku:'REC-STD-24V-40A', esName:'Rectificador Estándar', enName:'Standard Rectifier', category:'Onshore', icon:'zap', photo:'assets/rectifier-pcc.jpg', esDesc:'Unidad de corriente impresa de uso general para ductos y tanques enterrados.', enDesc:'General-purpose impressed-current unit for buried pipelines and tanks.' },
    { sku:'REC-PRT-12V-15A', esName:'Rectificador Portátil', enName:'Portable Rectifier', category:'Terreno',  icon:'battery-charging', photo:'assets/rectifier-portable-pcc.jpg', esDesc:'Compacto, para inspecciones de campo y ensayos temporales.', enDesc:'Compact unit for field inspections and temporary testing.' },
    { sku:'REC-MLT-48V-120A',esName:'Rectificador Múltiple', enName:'Multiple Rectifier', category:'Multi-circuito', icon:'layers-3', photo:'assets/rectifier-standard-pcc.jpg', esDesc:'Control simultáneo de hasta 6 circuitos independientes.', enDesc:'Simultaneous control of up to 6 independent circuits.' },
    { sku:'REC-AUT-24V-80A', esName:'Rectificador Automático', enName:'Automatic Rectifier', category:'Monitoreo', icon:'activity', photo:'assets/rectifier-automatic-pcc.png', esDesc:'Regulación automática de corriente con telemetría en tiempo real.', enDesc:'Automatic current regulation with real-time telemetry.' },
    { sku:'REC-SOL-24V-60A', esName:'Rectificador Solar', enName:'Solar Rectifier', category:'Off-grid', icon:'sun', photo:'assets/rectifier-solar-pcc.png', esDesc:'Paneles fotovoltaicos para zonas sin red eléctrica.', enDesc:'Photovoltaic panels for off-grid locations.' },
  ],
  supplyCats: [
    { id:'rect', icon:'zap', es:'Rectificadores', en:'Rectifiers', esD:'Estándar, portátil, múltiple, automático y solar.', enD:'Standard, portable, multiple, automatic and solar.' },
    { id:'anod', icon:'rocket', es:'Ánodos de sacrificio', en:'Sacrificial anodes', esD:'Zinc, aluminio y magnesio para estructuras sumergidas o enterradas.', enD:'Zinc, aluminum and magnesium for submerged or buried structures.' },
    { id:'iccp', icon:'plug-zap', es:'Ánodos de corriente impresa', en:'Impressed current anodes', esD:'Placas, barras y mallas para CP alimentado por fuente externa.', enD:'Plates, bars and mesh for externally powered CP.' },
    { id:'offs', icon:'anchor', es:'Sistemas para off-shore', en:'Off-shore systems', esD:'Accesorios y equipos para plataformas y estructuras marinas.', enD:'Accessories and equipment for platforms and marine structures.' },
    { id:'ac',   icon:'waves', es:'Mitigación de interferencias AC', en:'AC interference mitigation', esD:'Equipos y diseño para paralelismos con líneas de transmisión.', enD:'Equipment and design for parallelism with transmission lines.' },
    { id:'coat', icon:'paint-bucket', es:'Recubrimientos y accesorios', en:'Coatings & accessories', esD:'Resinas epóxicas, cintas y protecciones para uniones.', enD:'Epoxy resins, tapes and joint protection.' },
    { id:'jb',   icon:'box', es:'Cajas de unión / junction boxes', en:'Junction boxes', esD:'Conexiones, accesos de inspección y terminales.', enD:'Connections, inspection access and terminals.' },
    { id:'ref',  icon:'crosshair', es:'Electrodos de referencia', en:'Reference electrodes', esD:'Para medición y monitoreo de potenciales.', enD:'For potential measurement and monitoring.' },
    { id:'cbl',  icon:'cable', es:'Cables y auxiliares', en:'Cables & auxiliaries', esD:'Cables aislados, revestimientos y conectores.', enD:'Insulated cables, sheathing and connectors.' },
    { id:'tst',  icon:'gauge', es:'Equipos de prueba y monitoreo', en:'Test & monitoring equipment', esD:'Estaciones de prueba, equipos portátiles y monitoreo remoto.', enD:'Test stations, portable equipment and remote monitoring.' },
    { id:'mon',  icon:'radio', es:'Sistemas de monitoreo remoto', en:'Remote monitoring systems', esD:'Supervisión en tiempo real del desempeño del sistema CP.', enD:'Real-time supervision of CP system performance.' },
    { id:'stn',  icon:'map-pin', es:'Estaciones de prueba', en:'Test stations', esD:'Acceso a mediciones de potencial en puntos clave del sistema.', enD:'Access to potential measurements at key system points.' },
  ],
  projects: [
    { title:'Oleoducto Caño Limón–Coveñas', sector:'oil',     year:'2024', loc:'Colombia · 780 km', esScope:'Rehabilitación del sistema de CP y telemetría en toda la línea.', enScope:'CP system rehabilitation and telemetry along the full line.' },
    { title:'Puerto de Buenaventura',       sector:'marine',  year:'2024', loc:'Colombia · Pacífico', esScope:'Protección catódica de pilotes y tablestacados del muelle 7.', enScope:'Cathodic protection of piles and sheet piling at pier 7.' },
    { title:'Subestación Chilca',           sector:'power',   year:'2024', loc:'Perú · Lima',       esScope:'Sistema de puesta a tierra y mitigación AC para líneas de 220 kV.', enScope:'Grounding system and AC mitigation for 220 kV lines.' },
    { title:'Terminal LNG Costa del Golfo', sector:'oil',     year:'2025', loc:'USA · Texas',       esScope:'Ingeniería de detalle de CP para tanques de almacenamiento criogénico.', enScope:'CP detail engineering for cryogenic storage tanks.' },
    { title:'Planta de Tratamiento Tibitoc', sector:'industrial', year:'2023', loc:'Colombia · Cundinamarca', esScope:'CP en acueducto de tuberías metálicas de gran diámetro.', enScope:'CP for large-diameter metallic water network.' },
    { title:'Parque Solar La Loma',         sector:'power',   year:'2025', loc:'Colombia · Cesar',  esScope:'Evaluación y mitigación de interferencias AC en parque fotovoltaico.', enScope:'AC interference assessment and mitigation on PV farm.' },
  ],
  values: [
    { esName:'Confiabilidad', enName:'Reliability', esDesc:'Cuarenta y siete años operando sin interrupciones en tres países.', enDesc:'Forty-seven years operating without interruption across three countries.' },
    { esName:'Calidad certificada', enName:'Certified quality', esDesc:'ISO 9001, 14001, 45001 y personal NACE CP-4.', enDesc:'ISO 9001, 14001, 45001 and NACE CP-4 certified personnel.' },
    { esName:'Integralidad', enName:'Integrality', esDesc:'Ingeniería, suministro e instalación bajo un solo contrato.', enDesc:'Engineering, supply and installation under a single contract.' },
    { esName:'Seguridad', enName:'Safety', esDesc:'Cero incidentes mayores en proyectos onshore y offshore desde 2019.', enDesc:'Zero major incidents on onshore and offshore projects since 2019.' },
  ],
  certs: [
    { code:'ISO 9001:2015', desc:'Sistemas de gestión de calidad', no:'SG-2023009028-A' },
    { code:'ISO 14001:2015', desc:'Gestión ambiental',             no:'SG-2023009028-B' },
    { code:'ISO 45001:2018', desc:'Seguridad y salud en el trabajo', no:'SG-2023009028-F' },
    { code:'NACE International', desc:'CP-4 Cathodic Protection Specialist', no:'SG-2023009028-NK' },
  ],
  offices: [
    { country:'USA', flag:'🇺🇸', addr:'334 Grosvenor Loop, Davenport FL', email:'info-usa@pccintegrity.com', phone:'(+1) 281 693 6740' },
    { country:'Colombia', flag:'🇨🇴', addr:'Km 4.3 vía Suba–Cota, Cundinamarca', email:'info-co@pccintegrity.com', phone:'(+57) 1 680 9001', mobile:'(+57) 313 495 9571' },
    { country:'Perú', flag:'🇵🇪', addr:'Av. Primavera 607, Int. 501 San Borja, Lima', email:'info-pe@pccintegrity.com', phone:'(+51) 937 047 168' },
  ],
};
